site_name: ZipReport
site_description: PDF generation in Python with Jinja2 templates and client-side JS support
site_url: https://zipreport.github.io/zipreport/
theme:
  name: material
  palette:
  - scheme: slate
    primary: deep purple
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - scheme: default
    primary: deep purple
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo.png
  favicon: img/favicon.png
  language: en
repo_url: https://github.com/zipreport/zipreport
edit_uri: ''
nav:
  - index.md
  - install.md
  - how_it_works.md
  - build_templates.md
  - cli.md
  - faq.md
  - security.md
  - release-notes.md

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- mdx_include

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/zipreport/zipreport
